-- 코드를 입력하세요
# SELECT 
#     i.ANIMAL_ID,
#     i.ANIMAL_TYPE,
#     i.NAME
# FROM ANIMAL_INS AS i
# JOIN ANIMAL_OUTS AS o
# ON i.ANIMAL_ID = o.ANIMAL_ID
# WHERE i.SEX_UPON_INTAKE LIKE 'Intact%' AND
# o.SEX_UPON_OUTCOME NOT LIKE 'Intact%' 
# ORDER BY i.NAME;

SELECT I.ANIMAL_ID, I.ANIMAL_TYPE , I.NAME
  FROM ANIMAL_INS I
  JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
 WHERE I.SEX_UPON_INTAKE LIKE 'INTACT%'
   AND O.SEX_UPON_OUTCOME NOT LIKE 'INTACT%'
 ORDER BY I.ANIMAL_ID