-- 코드를 작성해주세요
SELECT 
    COUNT(*) AS FISH_COUNT,
    b.FISH_NAME
FROM 
    FISH_INFO a
JOIN
    FISH_NAME_INFO b
ON
    a.FISH_TYPE = b.FISH_TYPE
GROUP BY b.FISH_NAME
ORDER BY FISH_COUNT DESC;


# SELECT
#     FN.FISH_NAME,
#     COUNT(*) AS FISH_COUNT
# FROM FISH_INFO FI
# JOIN FISH_NAME_INFO FN
#   ON FI.FISH_TYPE = FN.FISH_TYPE
# GROUP BY FN.FISH_NAME
# ORDER BY FISH_COUNT DESC;