-- 코드를 입력하세요
SELECT
    u.USER_ID,
    u.NICKNAME,
    SUM(b.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS b
JOIN USED_GOODS_USER AS u
    ON b.WRITER_ID = u.USER_ID
WHERE b.STATUS = 'DONE'
GROUP BY u.USER_ID, u.NICKNAME  -- 회원 단위로 그룹화
HAVING SUM(b.PRICE) >= 700000  -- 집계 함수 조건
ORDER BY TOTAL_SALES ASC; 