-- 코드를 작성해주세요
# SELECT
#     i.ITEM_ID,
#     i.ITEM_NAME,
#     i.RARITY
# FROM ITEM_INFO i
# JOIN ITEM_TREE t ON i.ITEM_ID = t.PARENT_ITEM_ID
# JOIN ITEM_INFO r ON t.ITEM_ID = r.ITEM_ID
# WHERE i.RARITY = 'RARE'
# ORDER BY i.ITEM_ID DESC;

select t.ITEM_ID, i.ITEM_NAME, i.RARITY
from ITEM_INFO i
join ITEM_TREE t on i.ITEM_ID = t.ITEM_ID
where PARENT_ITEM_ID in (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
order by ITEM_ID desc;