-- 코드를 입력하세요
# SELECT ICECREAM_INFO.FLAVOR 
# FROM FIRST_HALF JOIN ICECREAM_INFO ON ICECREAM_FLAVOR.FLAVOR = FIRST_HALF.FLAVOR
# WHERE FIRST_HALF.TOTAL_ORDER > 3000 AND
#     ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based'
# ORDER BY TOTAL_ORDER DESC;


# SELECT a.FLAVOR
# FROM FIRST_HALF a JOIN ICECREAM_INFO b ON a.FLAVOR = b.FLAVOR
# WHERE a.TOTAL_ORDER > 3000
# and b.INGREDIENT_TYPE = 'fruit_based'
# ORDER BY a.TOTAL_ORDER DESC

# SELECT ICECREAM_INFO.FLAVOR 
# FROM FIRST_HALF, ICECREAM_INFO
# WHERE FIRST_HALF.TOTAL_ORDER > 3000 AND
#     ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based'
# ORDER BY TOTAL_ORDER DESC;

SELECT a.FLAVOR
FROM FIRST_HALF a JOIN ICECREAM_INFO b ON a.FLAVOR = b.FLAVOR
WHERE a.TOTAL_ORDER > 3000 AND
    b.INGREDIENT_TYPE = 'fruit_based'
ORDER BY a.TOTAL_ORDER DESC;