-- 코드를 작성해주세요
SELECT
    SUM(g.SCORE) AS SCORE,
    g.EMP_NO,
    e.EMP_NAME,
    e.POSITION,
    e.EMAIL
FROM HR_GRADE g
JOIN HR_EMPLOYEES e
ON g.EMP_NO = e.EMP_NO
GROUP BY g.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;
